---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: CentOS-7-x86_64-Vagrant-1902_01.VirtualBox
    driver:
            box: CentOS-7-x86_64-Vagrant-1902_01.VirtualBox
            box_url: http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1902_01.VirtualBox.box
            network: 
              - ["forwarded_port", {guest: 8001, host: 8001}]
              - ["forwarded_port", {guest: 8002, host: 8002}]
              - ["forwarded_port", {guest: 8003, host: 8003}]
              - ["forwarded_port", {guest: 8004, host: 8004}]

suites:
  - name: default
    run_list:
      - recipe[webapp_frontend::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
